apiVersion: v1
kind: Service
metadata:
 labels:
  service-label-key: jenkins
 name: jenkins
spec:
 type: NodePort
 ports:
 - port: 8080
   protocol: TCP
   nodePort: 30017
# - port: 8082
 #  protocol: TCP
  # nodePort: 30000
 selector:
  app: jenkins
