apiVersion: v1
kind: Service
metadata:
 labels:
  service-label-key: jenkins
 name: jenkins
spec:
 type: NodePort
 ports:
 - port: 8080
   protocol: TCP
   nodePort: 30017
   name: app
 - port: 50000
   protocol: TCP
   nodePort: 30018
   name: jnlp
 selector:
  app: jenkins
